const gridData = [
    {
      id: 1,
      title: "KEK serve in Goal 1",
      description: "End poverty in all its forms anywhere",
      targets: "7",
      events: "137",
      publications: "50",
      applications: "1464",
      image: "/images/goal1.png",
      icon: "/images/E_SDG_PRINT-02.png",
    },
    {
      id: 2,
      title: "KEK serve in Goal 1",
      description: "End poverty in all its forms anywhere",
      targets: "7",
      events: "137",
      publications: "50",
      applications: "1464",
      image: "/images/goal2.png",
      icon: "/images/E_SDG_PRINT-02.png",
    },
    {
      id: 3,
      title: "KEK serve in Goal 1",
      description: "End poverty in all its forms anywhere",
      targets: "7",
      events: "137",
      publications: "50",
      applications: "1464",
      image: "/images/goal3.png",
      icon: "/images/E_SDG_PRINT-02.png",
    },
    {
      id: 4,
      title: "KEK serve in Goal 1",
      description: "End poverty in all its forms anywhere",
      targets: "7",
      events: "137",
      publications: "50",
      applications: "1464",
      image: "/images/goal4.png",
      icon: "/images/E_SDG_PRINT-02.png",
    },
    {
      id: 5,
      title: "KEK serve in Goal 1",
      description: "End poverty in all its forms anywhere",
      targets: "7",
      events: "137",
      publications: "50",
      applications: "1464",
      image: "/images/goal5.png",
      icon: "/images/E_SDG_PRINT-02.png",
    },
    {
      id: 6,
      title: "KEK serve in Goal 1",
      description: "End poverty in all its forms anywhere",
      targets: "7",
      events: "137",
      publications: "50",
      applications: "1464",
      image: "/images/goal6.png",
      icon: "/images/E_SDG_PRINT-02.png",
    },
    {
      id: 7,
      title: "KEK serve in Goal 1",
      description: "End poverty in all its forms anywhere",
      targets: "7",
      events: "137",
      publications: "50",
      applications: "1464",
      image: "/images/goal7.png",
      icon: "/images/E_SDG_PRINT-02.png",
    },
    {
      id: 8,
      title: "KEK serve in Goal 1",
      description: "End poverty in all its forms anywhere",
      targets: "7",
      events: "137",
      publications: "50",
      applications: "1464",
      image: "/images/goal8.png",
      icon: "/images/E_SDG_PRINT-02.png",
    },
  ];
  
  export default gridData;