const gridData = [
    {
      id: 1,
      title: "KEK serve in Goal 1",
      description: "End poverty in all its forms anywhere",
      targets: "7",
      events: "137",
      publications: "50",
      applications: "1464",
      image: "/goal1.png",
      icon: "/E_SDG_PRINT-02.png",
    },
    {
      id: 2,
      title: "KEK serve in Goal 1",
      description: "End poverty in all its forms anywhere",
      targets: "7",
      events: "137",
      publications: "50",
      applications: "1464",
      image: "/goal2.png",
      icon: "/E_SDG_PRINT-02.png",
    },
    {
      id: 3,
      title: "KEK serve in Goal 1",
      description: "End poverty in all its forms anywhere",
      targets: "7",
      events: "137",
      publications: "50",
      applications: "1464",
      image: "/goal3.png",
      icon: "/E_SDG_PRINT-02.png",
    },
    {
      id: 4,
      title: "KEK serve in Goal 1",
      description: "End poverty in all its forms anywhere",
      targets: "7",
      events: "137",
      publications: "50",
      applications: "1464",
      image: "/goal4.png",
      icon: "/E_SDG_PRINT-02.png",
    },
    {
      id: 5,
      title: "KEK serve in Goal 1",
      description: "End poverty in all its forms anywhere",
      targets: "7",
      events: "137",
      publications: "50",
      applications: "1464",
      image: "/goal5.png",
      icon: "/E_SDG_PRINT-02.png",
    },
    {
      id: 6,
      title: "KEK serve in Goal 1",
      description: "End poverty in all its forms anywhere",
      targets: "7",
      events: "137",
      publications: "50",
      applications: "1464",
      image: "/goal6.png",
      icon: "/E_SDG_PRINT-02.png",
    },
    {
      id: 7,
      title: "KEK serve in Goal 1",
      description: "End poverty in all its forms anywhere",
      targets: "7",
      events: "137",
      publications: "50",
      applications: "1464",
      image: "/goal7.png",
      icon: "/E_SDG_PRINT-02.png",
    },
    {
      id: 8,
      title: "KEK serve in Goal 1",
      description: "End poverty in all its forms anywhere",
      targets: "7",
      events: "137",
      publications: "50",
      applications: "1464",
      image: "/goal8.png",
      icon: "/E_SDG_PRINT-02.png",
    },
  ];
  
  export default gridData;